theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
author: Copyright 2024 Steven Tilashalski All Rights Reserved
include:
  - index.md
  - README.md
header_pages:
  - index.md
  - overview.md
  - toc.md
  - clips.md
