theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
header_pages:
  - overview.md
  - README.md
  - recipes/desserts/richmond.md
